# Generated by Django 2.0 on 2018-06-12 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('classroom_id', models.AutoField(primary_key=True, serialize=False)),
                ('campus', models.PositiveSmallIntegerField(choices=[(0, '紫金港'), (1, '玉泉'), (2, '西溪'), (3, '华家池')], default=0, verbose_name='校区')),
                ('building', models.CharField(max_length=20, verbose_name='教学楼')),
                ('room', models.CharField(max_length=20, verbose_name='教室')),
                ('classroom_capacity', models.IntegerField(verbose_name='容量')),
            ],
        ),
        migrations.CreateModel(
            name='course_teacher_time_classroom_relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=5, verbose_name='时间')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_rid', to='auto_course.ClassRoom')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_cid', to='authentication.Course')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_tid', to='authentication.Faculty')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=50, verbose_name='标题')),
                ('content', models.TextField(verbose_name='请求内容')),
                ('status', models.SmallIntegerField(choices=[(0, '未处理'), (1, '已解决'), (2, '无法解决')], default=0, verbose_name='处理状态')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_tid', to='authentication.Faculty')),
            ],
        ),
    ]
