# Generated by Django 2.0 on 2018-06-05 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0003_auto_20180603_0016'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('classroom_id', models.AutoField(primary_key=True, serialize=False)),
                ('classroom_location', models.CharField(max_length=50, unique=True, verbose_name='地点')),
                ('classroom_capacity', models.IntegerField(verbose_name='容量')),
            ],
        ),
        migrations.CreateModel(
            name='course_teacher_time_classroom_relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=5, verbose_name='时间')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_rid', to='auto_course.ClassRoom')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_cid', to='authentication.Course')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_tid', to='authentication.Faculty')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('statue', models.IntegerField()),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_tid', to='authentication.Faculty')),
            ],
        ),
    ]
